esphome:
  name: esp-plug
  friendly_name: ESP Plug
  name_add_mac_suffix: true

bk72xx:
  board: generic-bk7231n-qfn32-tuya

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_api_pass

ota:
  - platform: esphome
    password: !secret esphome_ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESP-Plug"
    password: "password"

logger:

web_server:

captive_portal:

mdns:

debug:
  update_interval: 60s

substitutions:
  bl0937_voltage_divider: "750"
  bl0937_current_resistor: "0.0025 ohm"

text_sensor:
  - platform: libretiny
    version:
      name: LibreTiny Version

binary_sensor:
  - platform: gpio
    id: binary_switch_1
    pin:
      number: P26
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
        - switch.toggle: switch_1

switch:
  - platform: gpio
    id: switch_1
    name: Socket
    pin: P24
    restore_mode: ALWAYS_ON 

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
    update_interval: 60s
  - platform: hlw8012
    model: BL0937
    cf_pin:
      number: P7
      inverted: true
    cf1_pin:
      number: P6
      inverted: true
    sel_pin:
      number: P8
      inverted: true
    current:
      name: Current
    voltage:
      name: Voltage
    power:
      name: Power
    energy:
      name: Energy
    voltage_divider: $bl0937_voltage_divider
    current_resistor: $bl0937_current_resistor
    update_interval: 60s